version: "3.8"

services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"   # Puerto universal de LocalStack
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"